---
- set_fact:
    putit_application: "{{ lookup('env', 'PUTIT_APPLICATION') }}"
    putit_version: "{{ lookup('env', 'PUTIT_APPLICATION_VERSION') }}"
    putit_env: "{{ lookup('env', 'PUTIT_ENV') }}"
    putit_logs_url: "{{ lookup('env', 'PUTIT_RESULT_URL') }}/logs"

- name: Create install dirs
  file: 
    path="{{item.value.properties.install_dir}}/{{putit_env}}/{{ansible_ssh_user}}" 
    state=directory 
    mode=0755 
    owner="{{ansible_ssh_user}}"
  with_dict: "{{ artifacts }}"

- name: Copy artifacts
  copy: 
    src="{{item.value.properties.source_path}}" 
    dest="{{item.value.properties.install_dir}}/{{putit_env}}/{{ansible_ssh_user}}"
    mode="{{item.value.properties.mode}}" 
    backup=yes
  with_dict: "{{ artifacts }}" 

- name: Debug message
  debug:
    msg: "Deploying application {{ putit_application }} with version {{ putit_version }} on environment {{ putit_env }}. Logs: {{ putit_logs_url }}"

